### PR TITLE
Update the project to use dhall-kubernetes v7.0.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MartinPotier** [comment]
@oded-dd @ShauliSolomovich are you able to have a look?

**Review by oded-dd — APPROVED** [review]

**Comment by MartinPotier** [comment]
Uh, need to sign my commit apparently

**Comment by MartinPotier** [comment]
Ok, should be all signed up now. Merge at will (I apparently cannot)

**Comment by MartinPotier** [comment]
@oded-dd @ShauliSolomovich what would be the next steps for merging?

**Pull request merged**
